---
title: "prepare-data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{prepare-data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(drtplanr)
```

```{r eval=FALSE}
library(hereR)
library(sf)


## HERE API: Station, isoline and traffic
set_key("<YOUR API KEY>")
geo <- geocode("Jegenstorf Bahnhof RBS, Bern, Schweiz") %>% st_transform(2056)
sta <- station(geo, radius = 2000, results = 50) %>% st_transform(2056)
aoi <- isoline(sta[2, ], mode = "car", range = 3.25*60, traffic = FALSE) %>% st_transform(2056)
st_write(aoi, "data/prep.gpkg", layer = "aoi", quiet = TRUE)


## STATPOP 2018
pop <- fread("data/statpop/STATPOP2018G.csv")
pop$x <- pop$E_KOORD + 50
pop$y <- pop$N_KOORD + 50
pop$n <- pop$B18BTOT
pop <-
  pop[, c("x", "y", "n")] %>% 
  as.data.frame() %>% 
  st_as_sf(coords = c("x", "y")) %>% 
  st_set_crs(2056) %>% 
  st_transform(4326)
st_write(pop, "data/prep.gpkg", layer = "pop", quiet = TRUE)
```
